name: Simple_work
env:
  MY_APP_NAME: "My_App"
  MY_PACKAGE_NAME: "Myapp-version-${{ github.sha }}"
on:
  push:
    branches:
      - main
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello WOrld From Job-1"
      - name: Multi Command
        run: |
              touch 1.txt
              ls -la
              echo "My Application name is: ${{ env.MY_APP_NAME }}"
              echo "VAR1 value is:${{ env.VAR1 }}"
              pwd
      - name: sleep
        run: sleep 3

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    env:
      VAR1: "This is variable- 1"
      VAR2: "This is variable- 2"
    steps:
       - name: Print Hello
         run: echo "VAR1 value is:${{ env.VAR1 }}"
       - name: Print Name
         run: echo "My Application name is :${{ env.MY_PACKAGE_NAME }}"
       - name: sleep
         run: sleep 3
  
