name: Simple_work
env:
  MY_APP_NAME: "My_App"
  MY_PACKAGE_NAME: "Myapp-version-${{ github.sha }}"
on:
  push:
    branches:
      - main
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello WOrld From Job-1"
      - name: Git clone my repository
        uses: actions/checkout@v2
        
      - name: Multi Command
        run: |
              touch 9.txt
              ls -la
              echo "My Application name is: ${{ env.MY_APP_NAME }}"
              echo "VAR1 value is:${{ env.VAR1 }}"
              pwd
              
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    env:
      VAR1: "This is variable- 1"
      VAR2: "This is variable- 2"
    steps:
       - name: Print env Vars
         run: | 
           echo "VAR1 value is:${{ env.VAR1 }}"
           echo "VAR1 value is:${{ env.VAR2 }}"
           echo "this is my local var :$LOCAL_VAR"
           ls -la
           pwd
         env:
           LOCAL_VAR: "This is superr local Enviroment variable"
       - name: Git clone my repository
         uses: actions/checkout@v2
       - run: ls -la
       - name: Print Name
         run: echo "My Application name is :${{ env.MY_PACKAGE_NAME }}"

  
