name: Simple_work
on:
  push:
    branches:
      - main
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello WOrld From Job-1"
      - name: Multi Command
        run: |
              touch 1.txt
              ls -la
              pwd
      - name: sleep
        run: sleep 3

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
       - name: Print Hello
         run: echo "Hello WOrld From Job-2"
       - name: run ls -la
         run: ls -la
       - name: sleep
         run: sleep 3
  
